sonar.projectKey=Gingerminds-Symfony-Multisite
sonar.qualitygate.wait=true
sonar.sources=src,config
sonar.tests=tests
sonar.exclusions=vendor/**,var/**,src/Maker/skeleton/**
sonar.test.exclusions=tests/Application/var/**,tests/Application/assets/vendor/**
