<?php

declare(strict_types=1);

use Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator;

/*
 * Import from the project, after the core routes:
 *
 *     # config/routes/gingerminds_multisite.yaml
 *     gingerminds_multisite:
 *         resource: '@GingermindsMultisiteBundle/config/routes.php'
 *
 * The Site and Language CRUD routes are generated by the core
 * (`gingerminds_crud` loader of @GingermindsCoreBundle/config/routes.php).
 */
return static function (RoutingConfigurator $routes): void {
};
