<?php

declare(strict_types=1);

use Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator;

/*
 * Import from the project, after the core routes:
 *
 *     # config/routes/gingerminds_multisite.yaml
 *     gingerminds_multisite:
 *         resource: '@GingermindsMultisiteBundle/config/routes.php'
 *
 * The Site and Language CRUD routes (`gingerminds_multisite_site_*`,
 * `gingerminds_multisite_language_*`) are generated by the core
 * `gingerminds_crud` loader of @GingermindsCoreBundle/config/routes.php.
 */
return static function (RoutingConfigurator $routes): void {
    $routes->add('gingerminds_multisite_site_switch', '/%gingerminds_core.admin_prefix%/site-switch')
        ->controller('gingerminds_multisite.controller.admin.site_switch')
        ->methods(['POST']);

    $routes->add('gingerminds_multisite_translations_refresh', '/%gingerminds_core.admin_prefix%/translations/refresh')
        ->controller('gingerminds_multisite.controller.admin.translation_refresh')
        ->methods(['POST']);
};
